raytracer:
	clang++ -Wall src/*.cpp src/Raytracer/*.cpp src/Raytracer/Objects/*.cpp src/Raytracer/Scenes/*.cpp -o raytracer -I include -I include/HLSL

.PHONY: raytracer

clean:
	rm -f raytracer
	rm -f image.bmp
